### ISSUE TITLE
Feature Request: Please add option to hide the Email button

### ISSUE THREAD

**Issue by LazyLeecher** [PandaWood/ExceptionReporter.NET#10]
Some times I don't want the option to send emails do be show to the user in both screens (More/Less Details). Less headache.

Great lib, thanks a lot!

**Comment by FrancoTampieri** [comment]
I'm agree too

**Comment by PandaWood** [comment]
Yes, agreed. Just depends on the product. I'll see if I can work this in

**Comment by FrancoTampieri** [comment]
If u want I can fork project and give u an hand with a PR.

**Comment by PandaWood** [comment]
@drdran Yes by all means create a PR if you can. I'm on a Mac at home so can't easily test the UI of ExceptionReporter (which doesn't really work very well in Mono for some reason)

**Comment by PandaWood** [comment]
Post Script: this can now also be achieved by setting the config `SendMethod` to `ReportSendMethod.None`  - `ShowEmailButton` is left in for backward compatibility - and will override the aforementioned setting if both are set

See this fairly exhaustive set of test cases
```
[TestCase(ReportSendMethod.None, true,       ExpectedResult = false)]
[TestCase(ReportSendMethod.SMTP, true,       ExpectedResult = true)]
[TestCase(ReportSendMethod.SMTP, false,      ExpectedResult = false)]
[TestCase(ReportSendMethod.SimpleMAPI, true, ExpectedResult = true)]
[TestCase(ReportSendMethod.WebService, true, ExpectedResult = true)]
public bool Can_Determine_ShowEmailButton(ReportSendMethod method, bool show)
{
	_info.SendMethod = method;
	_info.ShowEmailButton = show;
	return _info.ShowEmailButton;
}
```
