### ISSUE TITLE
The message textbox is bigger then the screen

### ISSUE THREAD

**Issue by LazyLeecher** [PandaWood/ExceptionReporter.NET#11]
In the more detail screen the textbox that the user write his message (the yellow one) is sized bigger then the bottom of the window and hide the end of the user message.

Great lib, thanks a lot!

**Comment by PandaWood** [comment]
I wonder if this only happens on a certain resolution monitor or do you see it happen all the time?

**Comment by PandaWood** [comment]
No,it happens all the time. Somehow this flew passed me as I don't use that view myself
