### ISSUE TITLE
Feature Request: Add a new tab to show SQL code

### ISSUE THREAD

**Issue by LazyLeecher** [PandaWood/ExceptionReporter.NET#12]
When the error is database related I fill the necessity of a tab that I can put the sql command that generated the error. Also add a option to hide the tab or if the sql field is null to auto hide it.

Great lib, thanks a lot!

**Comment by PandaWood** [comment]
Hi @LazyLeecher - I think this ultimately the same as issue #6

Basically, an enhancement to add a way to add extra data (in your case, that data is SQL)
