### ISSUE TITLE
Ability to create GitHub issue from exception

### ISSUE THREAD

**Issue by PandaWood** [PandaWood/ExceptionReporter.NET#16]
Using this library would make this fairly easy - https://github.com/octokit/octokit.net
(caveat of requiring another dependency)

The code would probably give the error title to the issue and check for existing issues with the same name before creating a new one.

**Comment by PandaWood** [comment]
I looked it into this and it's not trivial - even with the Octokit.
It looks like the best way would be to create a GitHub App - in order to allow the developer to set restricted access to his repository but still allow new issues to be created.

**Comment by JavierCanon** [comment]
Or maybe the first easy way, if using an intermediate php or asp.net page for not make public your github key, and publish the issue.

**Comment by PandaWood** [comment]
I think I'll drop this issue in favor of the now-implemented `ReportSendMethod.WebService`
