### ISSUE TITLE
Add localization for other languages

### ISSUE THREAD

**Issue by PandaWood** [PandaWood/ExceptionReporter.NET#17]
Would be good to have the language on the buttons/messages adjust to the user's locale

**Comment by JavierCanon** [comment]
wich aproach you will use?, standard resources, xml, json? ex. [(https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager)](ResXManager) I can help with spanish

This project use resource files: [https://github.com/ravibpatel/CrashReporter.NET/tree/master/CrashReporter.NET](url)

**Comment by PandaWood** [comment]
Thanks, I only know about the .resx approach with WinForms - just like Crash-Reporter
I might do this on a branch - setup one or 2 languages, like Spanish, - then get someone helpful (in this case, you ;-)) to submit a PR on that

**Comment by JavierCanon** [comment]
Hello, you can check my [Fork](https://github.com/JavierCanon/ExceptionReporter.NET)

Im compiling in .net 4.7.2 for speed and others improvements like high DPI monitor support, but i think that compile in 4.0 without problems.  

Added translation support (spanish latin america demo), demo improvements, http php demos project, php github issue report example, php email send example.

**Comment by PandaWood** [comment]
This was added by issues #50 - one remaining task on that, is the assumption that the solution with the "new" project format is used
