### ISSUE TITLE
Send Anonymous Report Silently 

### ISSUE THREAD

**Issue by JavierCanon** [PandaWood/ExceptionReporter.NET#21]
Specify whether ExceptionReporte.NET should send anonymous crash report to that doesn't contain private information.  Only about 1/10 of users press "Send" button on crash reporting dialogs. And even less if there are required fields to fill.  Without sending anonymous reports most of the problems are hidden from the developer.

Option like: SendAnonymousReportSilently = true;

**Comment by PandaWood** [comment]
Thanks, yes I hadn't really thought of that.  
This seems like a good idea.
It would only work with email set to SMTP (not MAPI), of course - MAPI just opens the user's email client.
I suppose in sending an anonymous report, we should assume no screenshot sent?

**Comment by JavierCanon** [comment]
_we should assume no screenshot sent?_ 
R: Maybe optional, if the user allow it, like in android app's or chrome... you can ask in setup, and put the option in settings...

I think that is better to use a webservice (http / https (php, asp.net, etc.)) for sending clients reports, because you dont need to store user and password for smtp server in the app (maybe can relay the msg to a smtp server).  Smtp direct option is good for servers.

**Comment by PandaWood** [comment]
Right, I see your point with SMTP vs WebServices.
I'm just wondering - would you expect a WebService to basically be a POST to a configurable URL which contains a single packet of properties/JSON (maybe not even pre-defined) to be consumed?

**Comment by PandaWood** [comment]
BTW there is another issue I've just re-opened which is basically to [submit exception report to a webservice](https://github.com/PandaWood/ExceptionReporter.NET/issues/8)

So I will combine this request for "silent sending" as an additional feature on top of *sending via WebService*

**Comment by PandaWood** [comment]
Thinking about this, might not need another option...
Right now, to invoke the ExceptionReporter you call **Show**:
`ExceptionReporter.Show()` 
So, for a silent sending of a report, how about just calling a different method eg:
`ExceptionReporter.Send()`

**Comment by PandaWood** [comment]
I've implemented the latter option - ready for the next release 2.5

I also should have noticed and mentioned, that sending a report silently is already possible by using the `ExceptionReportGenerator.SendReportByEmail`- it's just not quite as simple as it will be with the new method.
