### ISSUE TITLE
Requested Clipboard operation did not succeed

### ISSUE THREAD

**Issue by keithyipkw** [PandaWood/ExceptionReporter.NET#41]
Windows clipboard API is unreliable. Failures are frequent. It is better to cancel the copy when any errors occur instead of quitting. At least it allows users to copy texts by selection and save their typed messages.

Steps:

1. Show an ExceptionReporter
2. Copy some texts in ExceptionReport, Visual Studio, Excel and etc
3. Click the "Copy Detail" or "Copy" button in ExceptionReporter
4. Repeat 2 and 3 until a popup "Requested Clipboard operation did not succeed"
5. ExceptionReport disappear

**Comment by Willy-Kimura** [comment]
Try inplementing [SharpClipboard](https://github.com/Willy-Kimura/SharpClipboard) for this.

**Comment by PandaWood** [comment]
Thanks @keithyipkw I should like to fix this
I don't think I've experienced it, but I believe it

**Comment by keithyipkw** [comment]
`Clipboard` mutation methods should be enclosed by try-catches. According to MS [doc](https://docs.microsoft.com/en-us/dotnet/api/system.windows.clipboard.setdataobject?view=netframework-4.8#System_Windows_Clipboard_SetDataObject_System_Object_System_Boolean_), `SetDataObject` may throw `ExternalException`. A [StackOverflow question](https://stackoverflow.com/questions/930219/how-to-handle-a-blocked-clipboard-and-other-oddities) also discussed the problem.

**Comment by PandaWood** [comment]
Sorry I didn't get around to this earlier.

I read the  [StackOverflow question](https://stackoverflow.com/questions/930219/how-to-handle-a-blocked-clipboard-and-other-oddities) and one of the main solutions is to basically call `Clipboard.Clear()` before `SetDataObject()`.
There are some other variations on that, like checking if the clipboard is being used by another app, but which seem like a lot more effort.

I did add some code today to at catch any exceptions during the clipboard operation and set the status/error text accordingly.

**Comment by PandaWood** [comment]
Since nothing seems to really fix this (even retrying/clearing the clipboard just makes it happen less often) - just handling the exception is the main fix here.
