### ISSUE TITLE
Programmatically save report

### ISSUE THREAD

**Issue by paintballkev812** [PandaWood/ExceptionReporter.NET#48]
Is there a way to programmatically save the report? I have an application would be used offline a majority of the time. My goal is in the event of no internet connection, I would like to save the report locally and on each subsequent startup, I would attempt to resend the bug report.

**Comment by PandaWood** [comment]
Yes you can programatically save the report - use the [ReportGenerator class](https://github.com/PandaWood/ExceptionReporter.NET/blob/master/src/ExceptionReporting/ReportGenerator.cs) directly - it's specifically designed for this.

Internally, when the `ExceptionReport` class sends a report it
1 - Generates a report using the `ReportGenerator`
2 - Sends it

So, just do (1) and do whatever you want with the report eg condensed code:
`new ReportGenerator(new ExceptionReportInfo()).Generate()`

Write your own code to save the string it returns (local file etc)

**Comment by paintballkev812** [comment]
Thanks!
