### ISSUE TITLE
Proposal: click on Save button save an archive with `FilesToAttach` instead of .txt

### ISSUE THREAD

**Issue by makeProjectGreatAgain** [PandaWood/ExceptionReporter.NET#53]
## Current behavior:
Click on *Save button* will save only *FILENAME.txt* file
![image](https://user-images.githubusercontent.com/24358142/99889531-32c5a780-2c67-11eb-9966-d8458b48ac19.png)

## Proposal:
Click on *Save button* save the archive with `FilesToAttach` and *report.txt*

## Motivation:
Allow to save report with `FilesToAttach`.
For example, there is (temporary) no connection to a network

**Comment by makeProjectGreatAgain** [comment]
If it's ok, I will implement it

**Comment by PandaWood** [comment]
Thanks for this, apologies I haven't merged it, I will do a quick review/check on the functionality and try merging it shortly.

**Comment by PandaWood** [comment]
Thanks pulled in
