### ISSUE TITLE
Disable Email button in Less-Detail view so users don't spam the button

### ISSUE THREAD

**Issue by jwallet** [PandaWood/ExceptionReporter.NET#55]
In this view
![image](https://user-images.githubusercontent.com/23088305/104095442-d04f5780-5264-11eb-8b86-43abed987a57.png)

When we hit the Email Company, the user has no feedback that the email is being proceeded or was sent, like we see in More-Detail view. So I rarely receive a report once, many people who send me reports do it like 5 to 10 times.

**Comment by makeProjectGreatAgain** [comment]
@jwallet What configuration do you use?
I tried Config with SendMethod = ReportSendMethod.SimpleMAPI and it was OK. I can't spam the button.

ExceptionReportPresenter.cs looks OK too
```
    /// <summary>
    /// Send the exception report using the configured send method
    /// </summary>
    public void SendReport()
    {
      this.View.EnableEmailButton = false;
      ...
```
