### ISSUE TITLE
Config option to respect user's privacy

### ISSUE THREAD

**Issue by CrushaKRool** [PandaWood/ExceptionReporter.NET#7]
Just a minor issue: it would be nice if there was a config option to disable the collection of identifying information **(user name** and **machine name** mostly). The respective entries should not be shown in the UI and be omitted from the generated output if the option is set.

The name of a users login name or the computer they are using is probably irrelevant for analyzing a bug in 99% of the cases. (Well, unless the application is being used in an internal business environment and not distributed for general public use.)
I've always felt a bit uneasy to have my application collect that kind of data when asking users for their cooperation by sending bug reports, and I can only assume that it might even have prevented some people from sending reports in the first place. Some people were actively censoring these details in the generated output before sending it in, but that's not really a hoop that I want to make them jump through for every bug report.

**Comment by PandaWood** [comment]
Yes, agreed. There is a rare time when the logged in user is relevant to us, but I'm still happy just take those fields out if it causes any issues.
