### ISSUE TITLE
Exception thrown in exceptionreport when Mailing

### ISSUE THREAD

**Issue by KlausWilly** [PandaWood/ExceptionReporter.NET#9]
Hi togehther;

I get this exception 
 
> The specified string is not in the form required for a subject.

when i try to send an Report to a mailadress.

The reason is the triggering exception has CRLF in the explanation
EX: Exception from path.combine(null,path2):
` Message = "The Value can not be null" & vbCrLf & "Parametername: path1"`
This Message is copied into the corresponding Mail field. 
But the Mail  doesn't accept it !! (two lines instead of one).

Can you filter out the disturbingly characters in the next Version?

That would be fine.

Best wishes Klaus

**Comment by PandaWood** [comment]
Thanks @KlausWilly 

Yes, we should parse the subject for being valid - I will label this to be fixed

**Comment by PandaWood** [comment]
I took the advice from the SO article - seems like it's a common problem - https://stackoverflow.com/questions/7239733/resolving-the-specified-string-is-not-in-the-form-required-for-a-subject
